// src/implementations/react/performance-test.component.jsx
import React from 'react';

import VirtualMachinesProvider from '../../helpers/virtual-machines-provider';
import VirtualMachinesTable from './virtual-machines-table.component.jsx';

const virtualMachinesProvider = new VirtualMachinesProvider(process.env.VIRTUAL_MACHINES);

class PerformanceTest extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            virtualMachines: virtualMachinesProvider.get()
        };
    }

    refresh() {
        virtualMachinesProvider.update();

        this.setState({
            virtualMachines: virtualMachinesProvider.get()
        })

        setTimeout(() => { this.refresh() }, 0);
    }

    componentDidMount() {
        this.refresh();
    }

    render() {
        return (
            <VirtualMachinesTable
                virtualMachines={this.state.virtualMachines}
            />
        );
    }
};

export default PerformanceTest;

// src/implementations/vue/performance-test.component.vue
<template lang="pug">
    virtual-machines-table(
        v-bind:virtual-machines="virtualMachines"
    )
</template>

<script>
    import VirtualMachinesProvider from '../../helpers/virtual-machines-provider';

    const virtualMachinesProvider = new VirtualMachinesProvider(process.env.VIRTUAL_MACHINES);

    export default {
        created() {
            this.refresh();
        },
        data: {
            virtualMachines: virtualMachinesProvider.get()
        },
        el: '#root',
        methods: {
            refresh() {
                virtualMachinesProvider.update();
                setTimeout(() => { this.refresh() }, 0);
            }
        }
    }
</script>
